name: Java Testson

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build and test
        run: |
          javac -d build src/*/*.java
          java -cp build org.junit.runner.JUnitCore src.*/*.class