name: Java Testson

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build and run project
        run: |
          javac -d target -cp "src:lib/gson-2.11.0.jar" src/*.java && java -cp "target:lib/gson-2.11.0.jar" Main